### PR TITLE
qat: make users explicitly opt in to have kernel mode compiled in

### PR DESCRIPTION
**Pull request by rojkov**

### CODE REVIEW

**Comment by mythi** [comment]
@rojkov thanks! this what I was thinking. let's hear from @kad and @bart0sh what they have to say about using tags.

**Comment by rojkov** [comment]
@bart0sh I've updated `Makefile` not to use build tags by default, please have another review round.

**Comment by kad** [comment]
Why do we want this? Also, can we have updated documentation for qat plugin to mention those build options with description?

**Comment by mythi** [comment]
@kad we want this to be able to ship without kernerdrv (and it's dependencies in the container) while still keeping that functionality in the repo.

**Comment by kad** [comment]
@mythi so, can we have documentation update that will describe that build mode?

**Comment by mythi** [comment]
@kad sure, I'll help with that. FWIW, we also have #197

**Comment by rojkov** [comment]
Added documentation update by Mikko.

**Comment by mythi** [comment]
`Jenkinsfile` needs updating too for `make test`

**Comment by rojkov** [comment]
Updated `Jenkinsfile`.

**Pull request merged**
