### PR TITLE
images: update license obligations

### PR DESCRIPTION
**Pull request by mythi**
Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>

### CODE REVIEW

**Review by bart0sh — DISMISSED** [review]
/lgtm

**Review by bart0sh — DISMISSED** [review]
/lgtm

**Comment by mythi** [comment]
let me update the commit message a bit still because it's misleading

**Comment by mythi** [comment]
@bart0sh ready to be merged

**Comment by mythi** [comment]
@ozhuraki looks OK?

**Review by ozhuraki — APPROVED** [review]
LGTM

**Pull request merged**
