### PR TITLE
docs + operator updates to 0.28.0

### PR DESCRIPTION
**Pull request by tkatila**

### CODE REVIEW

**Comment by eero-t** [comment]
`git grep -F 0.25` shows `INSTALL.md` referring to helm charts for releases going out of support (or already unsupported).

Will helm charts and `INSTALL.md` be also updated?

**Comment by tkatila** [comment]
> `git grep -F 0.25` shows `INSTALL.md` referring to helm charts for releases going out of support (or already unsupported).

INSTALL.md is referring to an example listing. It doesn't have to show the most recent state.
 
> Will helm charts and `INSTALL.md` be also updated?

There is a PR for helm charts: https://github.com/intel/helm-charts/pull/40

**Comment by mythi** [comment]
> > Will helm charts and `INSTALL.md` be also updated?
> 
> There is a PR for helm charts: [intel/helm-charts#40](https://github.com/intel/helm-charts/pull/40)

Talking about `INSTALL.md`, I can see at least the "Installing NFD" section *is* slightly outdated.

**Comment by tkatila** [comment]
> Talking about `INSTALL.md`, I can see at least the "Installing NFD" section _is_ slightly outdated.

That's true. I can update the NFD version and any other changes in another PR.

**Review by mythi — APPROVED** [review]

**Pull request merged**
