### PR TITLE
ci: check docs are buildable

### PR DESCRIPTION
**Pull request by rojkov**
Make sure docs are still buildable to avoid failures after PR merge when publishing the docs.

### CODE REVIEW

**Review by bart0sh — APPROVED** [review]
/lgtm

**Comment by mythi** [comment]
@rojkov want me to 'squash&merge'? :-)

**Comment by rojkov** [comment]
Sure, gladly!

**Comment by rojkov** [comment]
Oops. I was too quick to notice "me"....

But looks like the commit history is still there and the resulting merged commit even has got a reference to this PR in its message automatically.

**Pull request merged**
