### PR TITLE
operator: accept image SHA digests

### PR DESCRIPTION
**Pull request by mythi**

### CODE REVIEW

**Comment by mythi** [comment]
@hj-johannes-lee please check this proposal and test it out

/cc @chaitanya1731

**Comment by hj-johannes-lee** [comment]
For others also see, let me put the test results.

Before:
> $ kubectl apply -f deployments/operator/samples/deviceplugin_v1_dlbdeviceplugin.yaml 
Error from server (unable to parse version "@sha256:aa8a24770fa459fea7e8dea830d761c2a0435fcae76e4211712715a72a86e952": could not parse "@sha256:aa8a24770fa459fea7e8dea830d761c2a0435fcae76e4211712715a72a86e952" as version): error when creating "deployments/operator/samples/deviceplugin_v1_dlbdeviceplugin.yaml": admission webhook "vdlbdeviceplugin.kb.io" denied the request: unable to parse version "@sha256:aa8a24770fa459fea7e8dea830d761c2a0435fcae76e4211712715a72a86e952": could not parse "@sha256:aa8a24770fa459fea7e8dea830d761c2a0435fcae76e4211712715a72a86e952" as version


After:
> $ kubectl apply -f deployments/operator/samples/deviceplugin_v1_dlbdeviceplugin.yaml 
dlbdeviceplugin.deviceplugin.intel.com/dlbdeviceplugin-sample created


In case of wrong image name:
> $ kubectl apply -f deployments/operator/samples/deviceplugin_v1_dlbdeviceplugin.yaml 
Error from server (incorrect image name "intel-dlb-initcontainer-wrong". Make sure you use '<vendor>/intel-dlb-initcontainer.): error when creating "deployments/operator/samples/deviceplugin_v1_dlbdeviceplugin.yaml": admission webhook "vdlbdeviceplugin.kb.io" denied the request: incorrect image name "intel-dlb-initcontainer-wrong". Make sure you use '<vendor>/intel-dlb-initcontainer'.

**Comment by chaitanya1731** [comment]
Similar test results on OCP too.. 

CRs deploy successfully with SHAs (correct image name and SHA). 

For incorrect SHA length (random SHA key with length longer than expected) - 
> image

For incorrect image name - 
> image
> image

For incorrect SHA (with correct SHA length) - 
> CR is deployed but cannot pull image which is expected.. gives `ErrImagePull`
> image

**Comment by mythi** [comment]
@hj-johannes-lee @chaitanya1731 thanks! I improved the error handling / UX for the faulty SHA digests still. PTAL

**Review by tkatila — APPROVED** [review]
Looks good!

**Review by tkatila — APPROVED** [review]

**Review by hj-johannes-lee — DISMISSED** [review]

**Comment by chaitanya1731** [comment]
@mythi 
Done some testing again and the errors messages looks much better now - 

For incorrect SHA length
> Fix the following errors: 
> admission webhook "vsgxdeviceplugin.kb.io" denied the request: unable to parse version "055aa2fd127920b5fe8cfd73f8c2df13080093f1eab3ae8b19db0ea4b10739b1sadsda". Make sure it's either valid SHA digest or semver tag.: illegal version string "055aa2fd127920b5fe8cfd73f8c2df13080093f1eab3ae8b19db0ea4b10739b1sadsda"

For incorrect image name
> Fix the following errors:
> admission webhook "vsgxdeviceplugin.kb.io" denied the request: incorrect image name "intel-sgx-plugin-wrong@sha256". Make sure you use '<vendor>/intel-sgx-plugin'.

**Pull request merged**
