### PR TITLE
repo: drop .travis.yaml and update CODEOWNERS

### PR DESCRIPTION
**Pull request by mythi**

### CODE REVIEW

**Comment by rojkov** [comment]
The merge button is disabled because of image build failures. Which seem to be a ClearLinux issue again.

**Comment by mythi** [comment]
> The merge button is disabled because of image build failures.

I'll fix it in this PR (I was AFK for a while)

**Comment by mythi** [comment]
@bart0sh can you merge?

**Comment by bart0sh** [comment]
@mythi no, I can't. Only @kad can.

**Comment by bart0sh** [comment]
I was able to merge it as administrator. Not sure what happened as I was not able to that previously.

**Pull request merged**
