### PR TITLE
add missing mappings to the mapping collection

### PR DESCRIPTION
**Pull request by bart0sh**

### CODE REVIEW

**Review by rojkov — DISMISSED** [review]

**Comment by mythi** [comment]
I'm confused why crypto-perf image build fails with docker. I tried to debug it a bit today but no luck yet

**Comment by bart0sh** [comment]
@mythi do you think it's caused by this change?

**Comment by mythi** [comment]
@bart0sh no, #674 fails too.

**Review by mythi — COMMENTED** [review]
@bart0sh the file is also under `deployments/operator/samples/`. I guess that needs updating too?

**Comment by bart0sh** [comment]
@mythi should we symlink it?

**Comment by mythi** [comment]
@bart0sh IIRC kustomize does not accept symlinks which means `kubectl kustomize deployments/operator/samples` would fail in that case

**Comment by bart0sh** [comment]
@mythi updated, please review

**Review by mythi — APPROVED** [review]

**Review by rojkov — APPROVED** [review]

**Pull request merged**
