### PR TITLE
README: fix links and add docs for release-0.19

### PR DESCRIPTION
**Pull request by mythi**
Closes: #514 

/cc @intelkevinputnam does this look right?

### CODE REVIEW

**Review by bart0sh — APPROVED** [review]

**Comment by intelkevinputnam** [comment]
LGTM. @mythi while looking at this PR, I noticed something I missed earlier. In order for linking back to GitHub to work for directories set these values in the conf.py right after the initial GitHub configuration section:

``` python
sphinx_md_useGitHubURL = False
sphinx_md_githubFileURL = githubFileURL
sphinx_md_githubDirURL = githubDirURL
```

To your question in issue #514, you can reference a directory like this `[demo](demo)`. This will create a link back to github.

**Comment by mythi** [comment]
@intelkevinputnam thanks! I'll post v2 on Monday.

**Comment by mythi** [comment]
> `sphinx_md_useGitHubURL = False`

why false? My v2 is now per sphinx-md docs and it also drops `useGithubURL`.

**Comment by intelkevinputnam** [comment]
You're right. Should be True. Looks good.

**Comment by mythi** [comment]
@intelkevinputnam thanks!

@bart0sh @rojkov OK to merge

**Review by rojkov — APPROVED** [review]

**Pull request merged**
