### PR TITLE
images: move to Debian packaged accel-config

### PR DESCRIPTION
**Pull request by mythi**
Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>

### CODE REVIEW

**Comment by mythi** [comment]
> Looks OK, but tests fail:

yeah, they fail because I'm dropping that `idxd-reset.patch`. Looks like we still need it so we'll keep `accel-config-demo` as is for now.

**Comment by mythi** [comment]
@eero-t looks OK?

**Comment by eero-t** [comment]
@mythi Looks OK.

PS. I would have used `testing` instead of `unstable` though, because `unstable` is *known* to be occasionally broken, but that belongs to some other PR.

**Review by tkatila — APPROVED** [review]
looks good!

**Pull request merged**
