### PR TITLE
vpu: remove deprecated plugin

### PR DESCRIPTION
**Pull request by mythi**
The VPU plugin can only be used with devices that are
no longer supported by upper layers, such as OpenVINO.

The deprecation plan for the plugin was announced earlier
this year and v0.28 marks the date when the plugin is removed
from the repo.

Releases before v0.28 have the plugin available should it
be needed.

Fixes: #1422

### CODE REVIEW

**Review by tkatila — CHANGES_REQUESTED** [review]
```
$ grep -sir vpu *
demo/intelvpu-job.yaml:  name: intelvpu-demo-job
demo/intelvpu-job.yaml:    jobgroup: intelvpu-demo
demo/intelvpu-job.yaml:        jobgroup: intelvpu-demo
demo/intelvpu-job.yaml:          name: intelvpu-demo-job-1
demo/intelvpu-job.yaml:              vpu.intel.com/hddl: 1
deployments/vpu_plugin/overlays/xlink/add_command_args.yaml:  name: intel-vpu-plugin
deployments/vpu_plugin/overlays/xlink/add_command_args.yaml:      - name: intel-vpu-plugin
deployments/vpu_plugin/overlays/xlink/kustomization.yaml:    name: intel-vpu-plugin
deployments/vpu_plugin/base/intel-vpu-plugin.yaml:  name: intel-vpu-plugin
deployments/vpu_plugin/base/intel-vpu-plugin.yaml:    app: intel-vpu-plugin
deployments/vpu_plugin/base/intel-vpu-plugin.yaml:      app: intel-vpu-plugin
deployments/vpu_plugin/base/intel-vpu-plugin.yaml:        app: intel-vpu-plugin
deployments/vpu_plugin/base/intel-vpu-plugin.yaml:      - name: intel-vpu-plugin
deployments/vpu_plugin/base/intel-vpu-plugin.yaml:        image: intel/intel-vpu-plugin:devel
deployments/vpu_plugin/base/kustomization.yaml:  - intel-vpu-plugin.yaml
docs/extensions.rst:   ../cmd/vpu_plugin/README.md
README.md: * `vpu.intel.com`  : `hddl`
README.md:   * [intelvpu-job.yaml](demo/intelvpu-job.yaml)
```

Should we also remove the deployments? And there are some VPU mentions in the readme.

**Comment by mythi** [comment]
> Should we also remove the deployments? And there are some VPU mentions in the readme.

oops, yes of course.

**Review by tkatila — APPROVED** [review]

**Review by tkatila — APPROVED** [review]

**Comment by tkatila** [comment]
@hj-johannes-lee please review

**Review by hj-johannes-lee — COMMENTED** [review]
https://github.com/intel/intel-device-plugins-for-kubernetes/blob/main/.gitignore#L22
What about this?

**Comment by mythi** [comment]
> https://github.com/intel/intel-device-plugins-for-kubernetes/blob/main/.gitignore#L22 What about this?

fixed, thank you

**Review by hj-johannes-lee — APPROVED** [review]

**Review by tkatila — APPROVED** [review]

**Pull request merged**
