### PR TITLE
demo: Add DML demo

### PR DESCRIPTION
**Pull request by ozhuraki**
Issues:
https://github.com/intel/DML/pull/20
```
# docker run --rm -it -v /dev/iax/wq1.0:/dev/iax/wq1.0 intel/intel-dml-demo:devel
[...]
[==========] 714 tests from 125 test suites ran. (212116 ms total)
[  PASSED  ] 714 tests.
```

### CODE REVIEW

**Comment by eero-t** [comment]
Please check your Dockerfile with `hadolint`.

**Comment by ozhuraki** [comment]
@eero-t
Updated, please take a look

Changes:
- ADD -> COPY

**Comment by eero-t** [comment]
Hadolint will recommend also using apt-get and --no-install-recommends.

**Comment by mythi** [comment]
is it worth to maintain three images for accel-config/DML/QPL? 6e77933 gives an example how many places need modifications when `accel-config` is upgraded. This adds one more. What do you think?

**Comment by eero-t** [comment]
IMHO one _simple_ usage example per device plugin would be enough.  Links to external projects showing more complex usage would be a nice extra.

**Comment by ozhuraki** [comment]
@mythi 
It makes sense.
Changes:
- Use intel/intel-idxd-config-initcontainer:devel as an accel-config source

**Comment by mythi** [comment]
@ozhuraki 
> @mythi It makes sense. Changes:
> 
>     * Use intel/intel-idxd-config-initcontainer:devel as an accel-config source

This may trigger race conditions and unwanted behavior. My thinking was more about can we have just one "idxd demo" image.

@eero-t 
> IMHO one _simple_ usage example per device plugin would be enough. Links to external projects showing more complex usage would be a nice extra.

Currently we are evaluating DML and QPL for DSA and IAA, respectively. The both depend on "accel-config" lib. We also have `accel-config-demo` for basic unit tests that cover both DSA and IAA. As mentioned, my thinking was can we cover everything with just one image.

**Comment by ozhuraki** [comment]
@mythi
Updated, please take a look
Changes:
- Combined accel-config, DML and QPL demos

**Comment by mythi** [comment]
LGTM but can we also run these in e2e-dsa/e2e-iaa CI? @ozhuraki

**Comment by ozhuraki** [comment]
@mythi
Updated, changes:
- Run DML, QPL demos in e2e

**Comment by mythi** [comment]
@ozhuraki the logs look funny: 

```
2023-01-11T10:29:18.2110849Z [1mSTEP:[0m waiting for the IAA DML demo to succeed [38;5;243m01/11/23 12:28:10.583[0m
2023-01-11T10:29:18.2111235Z Jan 11 12:28:10.583: INFO: Waiting up to 5m0s for pod "iaa-accel-config-demo" in namespace "iaaplugin-8081" to be "Succeeded or Failed"
2023-01-11T10:29:18.2111595Z Jan 11 12:28:10.586: INFO: Pod "iaa-accel-config-demo": Phase="Succeeded", Reason="", readiness=false. Elapsed: 2.413565ms
2023-01-11T10:29:18.2112198Z Jan 11 12:28:10.586: INFO: Pod "iaa-accel-config-demo" satisfied condition "Succeeded or Failed"
```

It's not checking the right pod at all. It should not pass since DML is for DSA.

**Comment by mythi** [comment]
@ozhuraki see also #1301 as an additional idea

**Review by mythi — APPROVED** [review]

**Comment by bart0sh** [comment]
@ozhuraki do we run this in e2e?

**Comment by mythi** [comment]
> @ozhuraki do we run this in e2e?

@bart0sh I proposed to split the work so that this PR covers the Dockerfile changes only.

**Comment by bart0sh** [comment]
@ozhuraki ok, makes sense. merging.

**Pull request merged**
