### PR TITLE
deployments: update kube-rbac-proxy image and args

### PR DESCRIPTION
**Pull request by mythi**
draft until `v0.13.1` becomes available.

### CODE REVIEW

**Review by oreillymj — APPROVED** [review]
lgtm

**Review by bart0sh — APPROVED** [review]
/lgtm

**Comment by bart0sh** [comment]
@mythi looks like 0.13.1 is already available: https://console.cloud.google.com/gcr/images/kubebuilder/GLOBAL/kube-rbac-proxy

feel free to merge when needed

**Comment by mythi** [comment]
> @mythi looks like 0.13.1 is already available: https://console.cloud.google.com/gcr/images/kubebuilder/GLOBAL/kube-rbac-proxy
> 
> feel free to merge when needed

yes we can merge now. Now that the operator is deployed part of the tests, this PR was failing until 0.13.1 became available.

**Review by tkatila — APPROVED** [review]

**Pull request merged**
