### PR TITLE
move to k8s.io v1.24.0-rc.1

### PR DESCRIPTION
**Pull request by mythi**
Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>

### CODE REVIEW

**Comment by mythi** [comment]
looks like real errors with pod-security

**Comment by mythi** [comment]
depends: #987

**Comment by bart0sh** [comment]
@mythi as #987 has been merged, can you rebase this PR to see if the tests pass?

**Review by bart0sh — DISMISSED** [review]
/lgtm

**Comment by mythi** [comment]
pls merge before #991

**Comment by bart0sh** [comment]
@rojkov @kad PTAL

**Review by rojkov — APPROVED** [review]

**Pull request merged**
