### PR TITLE
e2e: Add DML, QPL demos

### PR DESCRIPTION
**Pull request by ozhuraki**

### CODE REVIEW

**Comment by tkatila** [comment]
Needs a rebase. What's the overall status for this?

**Comment by mythi** [comment]
> Needs a rebase. What's the overall status for this?

@ozhuraki

**Comment by hj-johannes-lee** [comment]
Since the basic structure of e2e tests is somewhat changed, I think you can just put your code into a new ginkgo.It().

ginkgo.It("deploys a [dml qml] pod", func(){
<your code>
})

**Comment by tkatila** [comment]
This seems outdated. I'd propose to close this. Any objections?

**Comment by mythi** [comment]
> This seems outdated. I'd propose to close this. Any objections?

No objections.

**Comment by tkatila** [comment]
Closing. Please re-open if this becomes relevant again.

**Pull request closed without merging**
