### PR TITLE
move topology testdata to ttar archive

### PR DESCRIPTION
**Pull request by uniemimu**
This adds ttar and moves topology testdata to a ttar archive. The purpose is to allow cloning the repo with folder-name challenged operating systems.

Signed-off-by: Ukri Niemimuukko <ukri.niemimuukko@intel.com>

### CODE REVIEW

**Review by mythi — DISMISSED** [review]
nit: we could also drop that dummy `go.mod` in `pkg/topology/testdata` now

**Review by rojkov — APPROVED** [review]
This is really nice!

**Comment by bart0sh** [comment]
@uniemimu topology.go was initially taken from https://github.com/intel/cri-resource-manager/tree/master/pkg/topology. At that time we decided not to depend on it as it would bring a lot of external dependencies to the project.
I think it would make sense to look if it makes sense to use it as a dependency and make this change in the cri-resource-manager.

**Comment by mythi** [comment]
> I think it would make sense to look if it makes sense to use it as a dependency and make this change in the cri-resource-manager.

@bart0sh I checked with @kad some time ago and the feedback was that we'd keep `pkg/topology` still in repo

**Review by bart0sh — APPROVED** [review]
/lgtm then

**Pull request merged**
