### PR TITLE
update supported releases table

### PR DESCRIPTION
**Pull request by bart0sh**
- fix broken link to project releases page
- add release 0.17 to the supported releases table

### CODE REVIEW

**Comment by mythi** [comment]
thanks for noticing! please update the table too, we now have release-0.17 too.

**Comment by bart0sh** [comment]
> thanks for noticing! please update the table too, we now have release-0.17 too.

I was going to do it in another PR, but can add it to this one if you prefer.

**Comment by mythi** [comment]
either way ;)

**Comment by bart0sh** [comment]
> another PR is OK

oops :)

**Comment by mythi** [comment]
merging regardless of CI status to get the "frontpage" up-to-date (we have the release)

**Pull request merged**
