### PR TITLE
Jenkinsfile: do not use parallel method

### PR DESCRIPTION
**Pull request by okartau**
Use of parallel creates race possibility as installation of
go happens in one part but is used in another.

### CODE REVIEW

**Comment by okartau** [comment]
I created a trivial fix for race condition. But when I look to these stages, I think it can be simplified more, as now we have stage with two substages in it, so I believe the end result is same if we just declare those two inner stages without having grouped by two, isnt it? We can rename the stages if the name part "Get requirements" is important.

**Comment by okartau** [comment]
syntax correctness even required that change, i.e. no extra stages around steps, force-pushed

**Review by mythi — APPROVED** [review]
thanks!

**Review by bart0sh — APPROVED** [review]
/lgtm

**Pull request merged**
