### PR TITLE
sgx: deprecate /dev/sgx/ mounts

### PR DESCRIPTION
**Pull request by hj-johannes-lee**
Closes: #725

Signed-off-by: Hyeongju Johannes Lee <hyeongju.lee@intel.com>

### CODE REVIEW

**Comment by mythi** [comment]
@hj-johannes-lee thanks! this looks ready as it is, we'll just have to wait.

**Comment by bart0sh** [comment]
@hj-johannes-lee @mythi does this PR still make sense? We should somehow proceed with it, shouldn't we?

**Comment by bart0sh** [comment]
I mean either drop it or fix conflict review and merge.

**Comment by hj-johannes-lee** [comment]
@bart0sh @mythi Aren't we just waiting for the new release of SGX SDK?

**Comment by hj-johannes-lee** [comment]
@mythi Ah, OK. I will change.

**Comment by hj-johannes-lee** [comment]
https://github.com/intel/linux-sgx/issues/795#issuecomment-1091600137
ready to review!

**Comment by mythi** [comment]
I started to think if this change comes too soon. would it make more sense at this point to change the plugin code so that it adds the mounts if only if the directory exist? then if someone needs those legacy symlinks can deploy with that `sgxdevices` volumeMount but we'd drop that by default.

**Comment by hj-johannes-lee** [comment]
@mythi Umm, I do not understand why would the deprecated one need to be kept..! Wouldn't the user who needs /dev/sgx/* should just use the new release of sdk or use old version the our plugin?

**Comment by mythi** [comment]
> @mythi Umm, I do not understand why would the deprecated one need to be kept..! Wouldn't the user who needs /dev/sgx/* should just use the new release of sdk or use old version the our plugin?

Sometimes it's just not that simple and I'm trying to think/understand how likely that is.

**Review by bart0sh — APPROVED** [review]
/lgtm

**Pull request merged**
