### PR TITLE
deployment fixes

### PR DESCRIPTION
**Pull request by mythi**
Fixes: #1212

### CODE REVIEW

**Comment by tkatila** [comment]
In `../fpga_plugin/base/role_binding.yaml` there is still "namespace: system". Should that also be removed?

**Comment by mythi** [comment]
> In `../fpga_plugin/base/role_binding.yaml` there is still "namespace: system". Should that also be removed?

Good point. I will have to investigate but it looks right now this is wrong at least.

**Comment by mythi** [comment]
> > In `../fpga_plugin/base/role_binding.yaml` there is still "namespace: system". Should that also be removed?
> 
> Good point. I will have to investigate but it looks right now this is wrong at least.

I restored it back to what it was.

**Review by tkatila — APPROVED** [review]

**Comment by mythi** [comment]
@hj-johannes-lee please approve

**Review by hj-johannes-lee — APPROVED** [review]

**Pull request merged**
