### PR TITLE
e2e: fix aftereach to be in the correct location

### PR DESCRIPTION
**Pull request by hj-johannes-lee**
Signed-off-by: Hyeongju Johannes Lee <hyeongju.lee@intel.com>

### CODE REVIEW

**Comment by mythi** [comment]
What's the problem it fixes?

**Comment by hj-johannes-lee** [comment]
Last time, when I was fixing e2e-dlb failing reported by Tuomas, I made this AfterEach() that undeploys.
But, if that is in "context", when there is another context in the future, same will happen again in the other context.
Currently, we have only one context in general, so we couldn't see any problem though.

**Comment by mythi** [comment]
> But, if that is inside one "context", then when there is another context in the future, same problem that Tuomas reported will happen again in the other context.

this part is missing from the commit message

**Review by mythi — APPROVED** [review]

**Comment by mythi** [comment]
> Wrote in the commit message!

I approved but just noticed your branch is a bit behind `main`. rebase?

**Pull request merged**
