### PR TITLE
priority: ci: use buildah from the distro

### PR DESCRIPTION
**Pull request by mythi**
Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>

### CODE REVIEW

**Review by okartau — APPROVED** [review]

**Comment by bart0sh** [comment]
I'd like to see all CI tests green before merging.

**Comment by mythi** [comment]
> I'd like to see all CI tests green before merging.

that's fine but this has no effect to `e2e-*`.

**Comment by bart0sh** [comment]
It affects images, so potentially can affect tests as well. Probability of this is low, but still not 0.

**Comment by mythi** [comment]
> I'd like to see all CI tests green before merging.

ready to go

**Review by bart0sh — APPROVED** [review]
/lgtm

**Pull request merged**
