### PR TITLE
simplify image push

### PR DESCRIPTION
**Pull request by rojkov**

### CODE REVIEW

**Comment by mythi** [comment]
I have no objections. The previous implementation had the idea that it's easier to push only 'images' and not 'demos' if necessary and that what gets built is the same set as what gets pushed (This PR fulfills the latter, sure)

**Comment by rojkov** [comment]
I see. We still can split the target to `make push-images`, `make push-demos` and `make push-all` if needed.

**Comment by mythi** [comment]
@rojkov it's OK right now, let's change it later if needed. Thanks for the PR, it is much cleaner

**Pull request merged**
