### PR TITLE
fix make format

### PR DESCRIPTION
**Pull request by bart0sh**
Makefile: fix format target
- Used gofmt instead of go fmt to show the changes and simplify the code
- Made 'make format' to exit with error when formatting is not correct

Fixed formatting errors in QAT plugin code to make Travis CI happy

Fixes: #57

### CODE REVIEW

**Comment by kad** [comment]
#56 has better fix for qat plugin

**Comment by bart0sh** [comment]
> #56 has better fix for qat plugin

mine was done by running gofmt -s -w. It was made for only one reson: fix CI breakage.

**Comment by mythi** [comment]
@bart0sh my editor did the same upon 'save' and that is why the same changes are in #56. I'm fine rebasing if this gets approved.

**Comment by kad** [comment]
ok, let's merge this and @mythi will rebase #56

**Pull request merged**
