### PR TITLE
qat: fix UIO mounts

### PR DESCRIPTION
**Pull request by mythi**
Fixes: #351

### CODE REVIEW

**Comment by bart0sh** [comment]
/LGTM, but tests are failing. It could be not related to this PR though.

**Comment by bart0sh** [comment]
@mythi Is it ok to merge it or you prefer to wait for pending reviews?

**Comment by mythi** [comment]
@bart0sh I'd need an OK from @swatisehgal or @nolancon  because I'm not aware if the functionality I'm removing is needed for something

**Comment by mythi** [comment]
@bart0sh @rojkov this is ready now

**Comment by bart0sh** [comment]
@mythi I can't merge it. It's "Waiting on code owner review from rojkov and/or swatisehgal."
@rojkov please review & merge. Thanks.

**Pull request merged**
