### PR TITLE
docs: fix remaining review comments

### PR DESCRIPTION
**Pull request by mythi**
Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>

### CODE REVIEW

**Review by bart0sh — DISMISSED** [review]
/lgtm

**Review by hj-johannes-lee — COMMENTED** [review]
I think it is not really important matter, but I do not have an idea about how titles are capitalized.
DEVEL.md 10-11:
* [Work with Intel Device Plugins operator modifications](#work-with-intel-device-plugins-operator-modifications)
* [Publish a New Version of the Intel Device Plugins Operator to operatorhub.io](#publish-a-new-version-of-the-intel-device-plugins-operator-to-operatorhub.io)
   
Do we need to capitalize them, or make other parts lowercases?

cmd/fpga_plugin/README.md 66:
> ### Modes and Configuration options

--> ### Modes and Configuration Options

One more thing to ask:
Do we use US english or UK english?
cmd/fpga_plugin/README.md 78:
> `af` mode. To utilise `region` mode, either modify the existing YAML appropriately,

DEVEL.md 259:
> package itself. The found devices are organized in an instance of

We use both '-ize' and '-ise' in documents.!

**Comment by mythi** [comment]
> Do we need to capitalize them, or make other parts lowercases?

I can fix these

> We use both '-ize' and '-ise' in documents.!

I'd say we don't change these.

**Review by bart0sh — APPROVED** [review]
/lgtm

**Pull request merged**
