### PR TITLE
chore: add gpu_fakedev to the extensions list

### PR DESCRIPTION
**Pull request by hugo-syn**
Add `gpu_fakedev` to the extensions list

### CODE REVIEW

**Comment by eero-t** [comment]
@tkatila, what do you think, does it make sense to mention fakedev in extensions list doc?

**Comment by tkatila** [comment]
Well, there are also items like "Intel FPGA test tool" in the extensions. So GPU fakedev would be fine in that sense. We're also missing the xpumanager-sidecar from the list.

**Comment by eero-t** [comment]
> Well, there are also items like "Intel FPGA test tool" in the extensions. So GPU fakedev would be fine in that sense.

Maybe there should be a separate testing tools list?

> We're also missing the xpumanager-sidecar from the list.

Oh, that should definitely be in the extension list.

**Comment by tkatila** [comment]
> > Well, there are also items like "Intel FPGA test tool" in the extensions. So GPU fakedev would be fine in that sense.
> 
> Maybe there should be a separate testing tools list?

I don't think that's necessary.

@hugo-syn can you also add xpu-manager-sidecar to the extensions list. Then I'm fine to merge this.

**Comment by mythi** [comment]
added a TODO in #1045 and closing

**Pull request closed without merging**
