### PR TITLE
sgx: use sgx-sdk-demo app instead of busybox

### PR DESCRIPTION
**Pull request by hj-johannes-lee**
Busybox does not run anything inside the container, and it does not test with real resources. Use sgx-sdk-demo image instead.

* #1469 should be merged first, and then this should be rebased.

### CODE REVIEW

**Comment by mythi** [comment]
one additional request: update `sgx-sdk-demo`  to 2.20 SDK and 1.17 DCAP

**Comment by hj-johannes-lee** [comment]
@mythi updated!

**Comment by mythi** [comment]
Thanks! Could you do the same for the aesmd image. Ready to move away from draft?

**Comment by mythi** [comment]
Nevermind, there is nothing version related in it

**Review by mythi — APPROVED** [review]

**Pull request merged**
