### PR TITLE
Add fake GPU device generator for scalability testing

### PR DESCRIPTION
**Pull request by eero-t**
The whole picture and earlier review comments are in the RFC PR https://github.com/intel/intel-device-plugins-for-kubernetes/pull/1104, from which this is split off.

Compared to RFC PR, I've moved / renamed generator code to `gpu_fakedev` / `gpu_fakedev.go` and added documentation + `intel-gpu-fakedev` container for it.

### CODE REVIEW

**Comment by eero-t** [comment]
The 7 plugin tests that **remain** in "expected" state show:
> Error: .github#L1
> An unexpected error has occurred and we've been automatically notified. Errors are sometimes temporary, so please try again.

What I should do next?

**Comment by eero-t** [comment]
While this adds new container for the devices project, program itself does not have any dependencies (outside of Golang standard libraries).

Currently it does not have unit tests, but I'm not sure what those would do, as this itself is a (scalability) testing tool (for GPU plugin).

Most relevant test would be whether GPU plugin reports expected number of GPUs for the content created by the tool, but because it's generating device files, running it requires either root or suitable capability for creating those.

**Comment by mythi** [comment]
> The 7 plugin tests that **remain** in "expected" state show:
> 
> > Error: .github#L1
> > An unexpected error has occurred and we've been automatically notified. Errors are sometimes temporary, so please try again.
> 
> What I should do next?

https://www.githubstatus.com/

**Comment by eero-t** [comment]
Updated doc + rebased on main now that GitHub problems are fixed, so that CI tests run for the first time.

**Comment by eero-t** [comment]
@mythi Any comments on this now that release is done?

**Review by uniemimu — APPROVED** [review]

**Review by bart0sh — COMMENTED** [review]
/lgtm

**Review by bart0sh — APPROVED** [review]

**Pull request merged**
