### PR TITLE
Add FPGA OpenCL Demo Screencast

### PR DESCRIPTION
**Pull request by linjiach**
1, added a second fpga device plugin demo using OpenCL workload
2, updated screencast thumbnail image from png to svg to show play buttons, and resized them to fit on screen better

### CODE REVIEW

**Comment by linjiach** [comment]
> @linjiach Thank you for the PR. It would be nice to have a screencast script included into this PR as well.

@bart0sh I'm thinking about adding the script when the container source is available too (we will have to check with sdl for docekerfile and opencl host program source etc). Do you prefer to add the script now? I think it's better to add the script later when those source files are available too, so users can try everything from beginning to end.

**Comment by linjiach** [comment]
@bart0sh  https://asciinema.org/a/344184 updated video

**Comment by bart0sh** [comment]
> I think it's better to add the script later when those source files are available too, so users can try everything from beginning to end.

Agree. The script and the pod yaml referring not yet available image should not be included into this PR.

**Comment by bart0sh** [comment]
@linjiach Do I understand correctly that this PR and screencast still needs to be updated as https://github.com/intel/intel-device-plugins-for-kubernetes/pull/412 has been merged?

**Comment by bart0sh** [comment]
@linjiach regarding using urls. I found that this can slow down the screencast due to more typing context and http download delays. We can keep using local clones I think.

**Pull request merged**
