### PR TITLE
add release 0.18 to the supported releases table

### PR DESCRIPTION
**Pull request by mythi**
Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>

### CODE REVIEW

**Comment by mythi** [comment]
@bart0sh can you merge? I'll take this in `release-0.18` to and then rebase #418

**Comment by mythi** [comment]
or @kad

**Comment by bart0sh** [comment]
@mythi I can't merge this. Only you and @kad can.

**Comment by mythi** [comment]
@bart0sh oh! I'll do it then

**Pull request merged**
