### PR TITLE
Upgrade to k8s v1.19.3

### LINKED ISSUE #452: update to k8s 1.19 APIs

### PR DESCRIPTION
**Pull request by rojkov**
Closes #452

### CODE REVIEW

**Review by bart0sh — APPROVED** [review]
/lgtm

**Review by mythi — COMMENTED** [review]
Looks great, thanks!

Lets wait a bit because of: `sigs.k8s.io/controller-runtime v0.7.0-alpha.6`

**Comment by mythi** [comment]
I tested SGX webhook and it works. However, I can see leader election permission errors like this:

```
E1105 09:57:35.558165       1 leaderelection.go:321] error retrieving resource lock inteldeviceplugins-system/d1c7b6d5.intel.com: leases.coordination.k8s.io "d1c7b6d5.intel.com" is forbidden: User "system:serviceaccount:inteldeviceplugins-system:default" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "inteldeviceplugins-system"
```

**Review by bart0sh — DISMISSED** [review]
/lgtm

tested fpga plugin functionality manually on the machine with 2 Inte Arria10 FPGA devices

**Comment by mythi** [comment]
@rojkov @bart0sh everything works for SGX and the errors are gone!

perhaps rebase+squash and then let's merge?

**Comment by bart0sh** [comment]
@mythi sgtm

**Comment by rojkov** [comment]
Ok, rebased and squashed.

**Review by bart0sh — APPROVED** [review]

**Pull request merged**
