### PR TITLE
docs: move away from 01.org doc links

### PR DESCRIPTION
**Pull request by mythi**
Closes: #684

### CODE REVIEW

**Review by bart0sh — APPROVED** [review]
/lgtm

**Comment by mythi** [comment]
> While checking the links, few things caught my eye on the SGX plugin page:
> 

Updated, thanks!

**Review by bart0sh — APPROVED** [review]

**Comment by bart0sh** [comment]
Merging is still blocked. @hj-johannes-lee can you review?

**Review by hj-johannes-lee — APPROVED** [review]
LGTM!

**Pull request merged**
