### PR TITLE
ci: fix builds with buildah

### PR DESCRIPTION
**Pull request by mythi**
Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>

### CODE REVIEW

**Comment by bart0sh** [comment]
@mythi Can you add an actual error to the description and commit message? It would help a lot to understand the fix.

**Comment by mythi** [comment]
@bart0sh I'm still trying to comprehend the core issue.  the new buildah (and dependencies) pushed on friday are broken.

**Comment by mythi** [comment]
@bart0sh @rojkov this fixes Github CI, Jenkins is still broken (the latest buildah from the repo fails to build images). Do you think we could rely on tools Github runners provide and accept this as a hot-fix while I fix Jenkins?

/cc @kad

**Comment by bart0sh** [comment]
@mythi This is ok as a quick workaround, but I'd prefer previous approach for a long term. It's more controllable and reproducible than relying on something that we can't change.

**Comment by mythi** [comment]
> It's more controllable and reproducible than relying on something that we can't change.

OTOH, I'm expecting the runner version upgrades are better validated. What we get from the repo now is broken and we cannot rollback either because only one version is provided... :-)

**Comment by bart0sh** [comment]
@mythi Can we have the same buildah version in Jenkins and the Github actions if we use buildah from the runner VM?
Would it make sense to use buildah from official Ubuntu repos for both GH actions and Jenkins environments?

**Comment by mythi** [comment]
> Can we have the same buildah version in Jenkins and the Github actions if we use buildah from the runner VM?

runner virtual env VMs are Github specific. I can make Github Actions work with libcontainers repo but we still have the open why the images fail to build with buildah 1.19.4.

I have submitted a buildah issue: https://github.com/containers/buildah/issues/3008

**Comment by bart0sh** [comment]
@mythi would it make sense to use buildah from official Ubuntu repositories https://packages.ubuntu.com/groovy/buildah ?
This way we can ensure we're using the same buildah version in GH actions and Jenkins.

**Comment by mythi** [comment]
@bart0sh I should have this fixed now. It's still not clear why buildah fails...

**Review by bart0sh — APPROVED** [review]
/lgtm

**Review by rojkov — APPROVED** [review]

**Pull request merged**
