### PR TITLE
dlb: update DLB to v8.0.0

### PR DESCRIPTION
**Pull request by hj-johannes-lee**
Signed-off-by: Hyeongju Johannes Lee <hyeongju.lee@intel.com>

### CODE REVIEW

**Comment by mythi** [comment]
I'd be curious to see what the application log is. You will need to adjust dlb.go to see because we log the pod output only when the pod is successful.

**Comment by hj-johannes-lee** [comment]
@mythi Yes, true.! I added a temporary commit that will be removed later after checking the logs and solving the problem of this pr.

**Comment by mythi** [comment]
@hj-johannes-lee I think we need to drop `e2e-dlb-spr` so we get this PR merged.

**Comment by hj-johannes-lee** [comment]
@mythi dropped!

**Review by mythi — DISMISSED** [review]
LGTM, OK to merge when moved away from draft and the backend is confirmed to run with the right driver version.

**Comment by hj-johannes-lee** [comment]
@mythi Done! Rabased also done.!

**Review by tkatila — APPROVED** [review]
lgtm

**Pull request merged**
