### PR TITLE
fix links by removing table

### LINKED ISSUE #1058: Broken deployments doc links
This page: https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/

Leads here: https://intel.github.io/intel-device-plugins-for-kubernetes/README.html

While rest of the links there seem to work, **all** the links in "Workload Authors" section are broken: https://intel.github.io/intel-device-plugins-for-kubernetes/README.html#workload-authors

PS. "Related code" section paragraph is missing period (".") from the end.

### PR DESCRIPTION
**Pull request by uniemimu**
As a workaround for broken links, this removes the Workload Authors
section table and replaces it with a list.

fixes #1058

Signed-off-by: Ukri Niemimuukko <ukri.niemimuukko@intel.com>

### CODE REVIEW

**Comment by eero-t** [comment]
While table looks visually nicer, it's better that links work.  +1

(Bug includes link to root cause explanation of Sphinx having issue generating links in tables correctly. Converting tables to lists is one workaround for that.)

**Comment by mythi** [comment]
> While table looks visually nicer, it's better that links work. +1

just thinking out loud: would it be better to keep table and just remove the links and just to "demo/foobar.yaml"?

**Comment by uniemimu** [comment]
> > While table looks visually nicer, it's better that links work. +1
> 
> just thinking out loud: would it be better to keep table and just remove the links and just to "demo/foobar.yaml"?

I think it is a good idea to have a link from which the users can take a look at easily (and quickly) how the yaml ought to look like. Searching through folders isn't that nice.

**Comment by mythi** [comment]
+1. did you test the links are generated properly after this?

**Comment by uniemimu** [comment]
> +1. did you test the links are generated properly after this?

No, I'll be trusting my luck. Revert if necessary..

**Review by mythi — APPROVED** [review]
tested and works as expected. Thanks!

**Pull request merged**
