### PR TITLE
gpu: add new nfd + monitoring + shared-dev deployment option

### PR DESCRIPTION
**Pull request by tkatila**
Closes: #1283
Signed-off-by: Tuomas Katila <tuomas.katila@intel.com>

### CODE REVIEW

**Comment by mythi** [comment]
while we're at it, maybe fix #1283 in a separate commit?

**Comment by eero-t** [comment]
/lgtm

CI checks seem just broken, as this does PR not touch anything related to the failing tests.

I don't see what's the problem with "iia", and "terrascan" & "sgx" fails to networking issues:

```
Run curl -sL "$(curl -sL https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz
Error: Process completed with exit code 3.
```

```
 error creating build container: 2 errors occurred while pulling:
 * initializing source docker://192.168.33.10:5000/golang:1.19-bullseye: reading manifest 1.19-bullseye in 192.168.33.10:5000/golang: manifest unknown: manifest unknown
 * reading blob sha256:32de3c850997ce03b6ff4ae8fb00b34b9d7d7f9a35bfcdb8538e22cc7b77c29d: Get "https://cache-registry.caas.intel.com/v2/cache/library/golang/blobs/sha256:32de3c850997ce03b6ff4ae8fb00b34b9d7d7f9a35bfcdb8538e22cc7b77c29d": context deadline exceeded
[2/2] STEP 1/9: FROM gcr.io/distroless/static
make: *** [Makefile:213: intel-sgx-initcontainer] Error 125
```

**Comment by tkatila** [comment]
> while we're at it, maybe fix #1283 in a separate commit?

sure

**Comment by mythi** [comment]
> > while we're at it, maybe fix #1283 in a separate commit?
> 
> sure

Apologies, CI has faulty mirror config and currently `registry.k8s.io` images are not pulled. We will fix it.

**Comment by mythi** [comment]
> /lgtm
> 
> CI checks seem just broken, as this does PR not touch anything related to the failing tests.
> 
> I don't see what's the problem with "iia", and "terrascan" & "sgx" fails to networking issues:

Right, they are not related to the PR content but random network glitches.

> 
> ```
> Run curl -sL "$(curl -sL https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz
> Error: Process completed with exit code 3.
> ```

this one has started to show up recently but I cannot think of the reason what might cause the flakiness.

**Comment by tkatila** [comment]
> ```
> Run curl -sL "$(curl -sL https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz
> Error: Process completed with exit code 3.
> ```

Return code 3 for curl is "malformed url". The inner curl can return empty when github.com starts rate limiting. It's actually fairly easy to trigger:
```
$ curl -sL "$(curl -sL https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz
$ echo $?
3
```

**Comment by mythi** [comment]
> > ```
> > Run curl -sL "$(curl -sL https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz
> > Error: Process completed with exit code 3.
> > ```
> 
> Return code 3 for curl is "malformed url". The inner curl can return empty when github.com starts rate limiting. It's actually fairly easy to trigger:
> 
> ```
> $ curl -sL "$(curl -sL https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz
> $ echo $?
> 3
> ```

Thanks for checking this! Perhaps we should switch to a URL we maintain ourselves?

```
https://github.com/tenable/terrascan/releases/download/v${TERRASCAN_VERSION}/terrascan_${TERRASCAN_VERSION}_Linux_x86_64.tar.gz
```

**Review by mythi — APPROVED** [review]

**Comment by mythi** [comment]
@uniemimu needs your approval

**Comment by tkatila** [comment]
> Thanks for checking this! Perhaps we should switch to a URL we maintain ourselves?
> 
> ```
> https://github.com/tenable/terrascan/releases/download/v${TERRASCAN_VERSION}/terrascan_${TERRASCAN_VERSION}_Linux_x86_64.tar.gz
> ```

I think it would help, but I'm not sure if it would completely get rid of the error. If the download link is also rate limited, the actual download could also break sometimes.

**Review by uniemimu — APPROVED** [review]

**Pull request merged**
