### PR TITLE
fpga: improve port init

### PR DESCRIPTION
**Pull request by bart0sh**
Used generic newPort API instead of device-specific
newDflPort and newIntelFpgaPort to initialize plugin.newPort.

### CODE REVIEW

**Comment by bart0sh** [comment]
@mythi @rojkov intel-gpu-initcontainer and openssl-qat-engine images failed to build. Can you look?

**Comment by uniemimu** [comment]
> @mythi @rojkov intel-gpu-initcontainer and openssl-qat-engine images failed to build. Can you look?

Looks like the typical random failures associated with trying to use clear linux for building. Nobody in their right mind would do such a thing unless the idea is to keep identifying clear linux issues.

**Comment by mythi** [comment]
@bart0sh I cannot find any errors in the CI history to see what went wrong. Looks like the builds are passing today?

**Review by mythi — COMMENTED** [review]
+1

**Pull request merged**
