### PR TITLE
Get rid of unused sysfsDir parameter

### PR DESCRIPTION
**Pull request by bart0sh**

### CODE REVIEW

**Review by tkatila — APPROVED** [review]
LGTM

**Comment by mythi** [comment]
We could also drop the `hostPath` volumes? https://github.com/intel/intel-device-plugins-for-kubernetes/blob/89c9dcf5f46cb2ec1e7817d7b812a3bfab6cfdc4/deployments/dsa_plugin/base/intel-dsa-plugin.yaml#L35-L37

**Review by hj-johannes-lee — COMMENTED** [review]
It seems that
deployments/dsa_plugin/base/intel-dsa-plugin.yaml
deployments/iaa_plugin/overlays/iaa_initcontainer/iaa_initcontainer.yaml
deployments/dsa_plugin/overlays/dsa_initcontainer/dsa_initcontainer.yaml
pkg/controller_test.go
pkg/controllers/dsa
pkg/controllers/iaa
also have /sys/bus/dsa

deployments/iaa_plugin/base/intel-iaa-plugin.yaml
has /sys/bus/iax

They are all removed?

**Comment by bart0sh** [comment]
> We could also drop the `hostPath` volumes?

We can't to my knowledge. How would plugin discover devices without access to sysfs?
hint: https://github.com/intel/intel-device-plugins-for-kubernetes/blob/main/cmd/dsa_plugin/dsa_plugin.go#L35

**Comment by bart0sh** [comment]
> In addition,
> 
> It seems that deployments/dsa_plugin/base/intel-dsa-plugin.yaml deployments/iaa_plugin/overlays/iaa_initcontainer/iaa_initcontainer.yaml deployments/dsa_plugin/overlays/dsa_initcontainer/dsa_initcontainer.yaml pkg/controller_test.go pkg/controllers/dsa pkg/controllers/iaa also have /sys/bus/dsa
> 
> deployments/iaa_plugin/base/intel-iaa-plugin.yaml has /sys/bus/iax
> 
> They are all removed?

not sure I follow. Can you elaborate?

**Comment by mythi** [comment]
> > We could also drop the `hostPath` volumes?
> 
> We can't to my knowledge. How would plugin discover devices without access to sysfs? hint: https://github.com/intel/intel-device-plugins-for-kubernetes/blob/main/cmd/dsa_plugin/dsa_plugin.go#L35

Right, I missed that `statePattern`.

**Review by mythi — APPROVED** [review]

**Comment by mythi** [comment]
> > In addition,
> > It seems that deployments/dsa_plugin/base/intel-dsa-plugin.yaml deployments/iaa_plugin/overlays/iaa_initcontainer/iaa_initcontainer.yaml deployments/dsa_plugin/overlays/dsa_initcontainer/dsa_initcontainer.yaml pkg/controller_test.go pkg/controllers/dsa pkg/controllers/iaa also have /sys/bus/dsa
> > deployments/iaa_plugin/base/intel-iaa-plugin.yaml has /sys/bus/iax
> > They are all removed?
> 
> not sure I follow. Can you elaborate?

I think it just refers to my comment which was limited to just one place.

**Pull request merged**
