### PR TITLE
demo: update idxd-config version to v3.5.0

### PR DESCRIPTION
**Pull request by mythi**

### CODE REVIEW

**Comment by mythi** [comment]
@ozhuraki @bart0sh I could use some help with this one. Can you try `e2e-iaa` locally?

**Comment by mythi** [comment]
@bart0sh @ozhuraki this is ready for review, finally! I had to disable some tests (`0x42` opcodes) to gnr passing (known issues). Let me know if you want detailed reasons for some of the changes and I'll update the commit message if needed

**Review by bart0sh — APPROVED** [review]
/lgtm

**Review by ozhuraki — APPROVED** [review]
LGTM

**Review by hj-johannes-lee — APPROVED** [review]
LGTM!

Didn't I already review this pr before? Is this a different pr?

**Comment by mythi** [comment]
> Didn't I already review this pr before? Is this a different pr?

It was the debug version in @bart0sh's repo

**Comment by hj-johannes-lee** [comment]
@mythi Ahaa.!! I could not notice..! haha.

**Pull request merged**
