### PR TITLE
Add CI Jenkins stage with test case for intel-device-plugin: QAT

### PR DESCRIPTION
**Pull request by obedmr**
This commit adds bash scripts with the proper granularity for each sub-stage,
needed for QAT device main stage validation.

squash for #231 

Signed-off-by: Rivera Gonzalez, Julio C <julio.c.rivera.gonzalez@intel.com>

### CODE REVIEW

**Comment by obedmr** [comment]
@mythi @kad - please review this squashed commit in replacement for #231, @juliocri is on vacation.

**Comment by mythi** [comment]
@obedmr did you find what's wrong with BMaaS?

**Comment by obedmr** [comment]
@mythi yes it was a network infra sporadic issue. Hope that will not happen again.

**Comment by mythi** [comment]
@obedmr can you re-push so that we get to test it?

/cc @chuyd @chavafg

**Comment by chuyd** [comment]
@mythi I re-triggered the tests for this PR

**Comment by mythi** [comment]
@chuyd how did it go?

**Pull request merged**
