### PR TITLE
e2e: make tests divided into smaller parts (DLB, DSA, IAA, QAT) 

### PR DESCRIPTION
**Pull request by hj-johannes-lee**
Restructure e2e tests from a single It() as follows:

Describe("device")
*BeforeEach("deploys plugin")
**Context("When device resources are available")
***BeforeEach("checks if resources are available")
****It("runs a pod requesting resources")
****It("runs another pod requesting resources if there is")

Signed-off-by: Hyeongju Johannes Lee <hyeongju.lee@intel.com>

### CODE REVIEW

**Comment by mythi** [comment]
> Additionally, fix grammar mistakes and typos

these can go to a separate PR

**Comment by hj-johannes-lee** [comment]
@mythi Sure, i will divide them.!

**Comment by hj-johannes-lee** [comment]
Updates:
FPGA has some problem, so I thought it would be good to do first the 4 device plugins that are used in SPR (DLB, DSA, IAA, QAT).

To do (maybe in another PR):
QAT4 - cy device is recognized as generic inside a VM.
DLB - pf device is recognized as vf inside a VM.

We need to deal with this matter.

**Comment by hj-johannes-lee** [comment]
Could you review? :)

**Comment by hj-johannes-lee** [comment]
@mythi @ozhuraki Could you review? :)

**Comment by mythi** [comment]
Is there a possibility this breaks if Ginkgo randomizes things differently? Now the test cases have a dependency and it might be that the demo app gets deployed before the plugin?

**Comment by hj-johannes-lee** [comment]
@mythi yes, I thought about that matter,, and there is 'ginkgo. Order' that makes everything run in order. Following ones are skipped in case previous It() fails.
I thought I put them already since no test got failed. Let me put it.

**Comment by mythi** [comment]
> there is 'ginkgo. Order'

randomisation is on purpose to ensure the tests are correctly written so I don't think we want to disable it

**Comment by hj-johannes-lee** [comment]
@mythi Umm, did I understand what you meant correctly? What 'randomization' do we have for now? We have only one It()!

**Comment by mythi** [comment]
> @mythi Umm, did I understand what you meant correctly? What 'randomization' do we have for now? We have only one It()!

I was reading this before asking my question https://onsi.github.io/ginkgo/#spec-randomization

**Comment by hj-johannes-lee** [comment]
I then suggest this way:

Describe ("device")
 - BeforeEach("deploys plugin")
   - Context("When device resources are available")
     - BeforeEach("checks if resources are available")
     - It("runs a pod requesting resources")
     - It("runs another pod requesting resources if there is") 

In this way, we can randomize specs and does not cause any problem no matter how many It()s exists.

**Comment by mythi** [comment]
> In this way, we can randomize specs and does not cause any problem no matter how many It()s exists.

The proposal looks much better and closer to what I originally had in mind with #1143

**Comment by hj-johannes-lee** [comment]
@mythi Thanks! :) I guess all ci passed.! Please review the code! :)
For the matter of GPU and FPGA, can I do in another PR later?

**Comment by mythi** [comment]
> @mythi Thanks! :) I guess all ci passed.! Please review the code! :) For the matter of GPU and FPGA, can I do in another PR later?

It's fine. For this PR, I'd suggest we change things to one commit per device.

**Comment by hj-johannes-lee** [comment]
@mythi Done.! What else would this pr you think need? :)

**Comment by hj-johannes-lee** [comment]
@ozhuraki Could you review?

**Review by mythi — DISMISSED** [review]

**Comment by hj-johannes-lee** [comment]
After this get merged, let me also make a pr for the improvement of documentations for e2e tests.!

**Review by mythi — APPROVED** [review]

**Pull request merged**
