### PR TITLE
Rework makefile

### PR DESCRIPTION
**Pull request by rojkov**
Reworked `Makefile` to add more granularity to build and image targets. Now it;s possible to build either all binaries or one specific binary.
Build all binaries:
```
$ make build
```
Build only `gpu_plugin`:
```
$ make gpu_plugin
```
Build all Docker images:
```
$ make images
```
Build only `intel-gpu-plugin` image:
```
$ make intel-gpu-plugin
```

Also a specific package can be tested with `coverage.html` autogenerated
```
$ make WHAT=internal/deviceplugin test
```

### CODE REVIEW

**Comment by kad** [comment]
looks good.

**Comment by bart0sh** [comment]
Should we update Travis-CI config to test new make targets?

**Comment by rojkov** [comment]
There're no new untested targets. This `make images` is just a restructured version of `make container` which isn't tested currently. I would add `make images` in a separate PR.

**Comment by bart0sh** [comment]
I meant 'make gpu_plugin' 'make fpga_plugin' etc.

**Comment by rojkov** [comment]
Those are tested implicitly through `make` (since `make` is an alias of `make all`, `make all` depends on `make build` and `make build` depends on both `make gpu_plugin` and `make fpga_plugin` and whatever else is going to be added in the `cmd` folder).

**Comment by swatisehgal** [comment]
Looks good Guys!

**Pull request merged**
